version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./scripts/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump:/dump
volumes:
  mongodb:
